package com.omgm.admin.main.beans;

import java.util.Date;

public class RoomReservationVO {
    private int ROOMRESERVATION_NO;
    private int ROOMRESERVATION_ROOMNO;
    private  int ROOMRESERVATION_ROOMPRICE;
    private String ROOMRESERVATION_ROOMNAME;
    private int ROOMRESERVATION_MEMBERNO;
    private Date ROOMRESERVATION_STAYDAY;
    private Date ROOMRESERVATION_PAYDAY;
    private int ROOMRESERVATION_FOODNO;
    private String ROOMRESERVATION_FOODNAME;
    private int ROOMRESERVATION_TOYNO;
    private String ROOMRESERVATION_TOYNAME;
    private String ROOMRESERVATION_PICKUPYN;
    private int ROOMRESERVATION_PICKUPTIME;
    private  String ROOMRESERVATION_PICKUPADDRESS;
    private String ROOMRESERVATION_PICKUPPHONENUM;
    private String ROOMRESERVATION_USEPOINTYN;
    private int  ROOMRESERVATION_USEPOINT;
    private int ROOMRESERVATION_PLUSPOINT;
    private int ROOMRESERVATION_FIANLFEE;
    private String day1;

    public String getDay1() {
        return day1;
    }

    public void setDay1(String day1) {
        this.day1 = day1;
    }

    public String getDay2() {
        return day2;
    }

    public void setDay2(String day2) {
        this.day2 = day2;
    }

    private String day2;

    public int getROOMRESERVATION_NO() {
        return ROOMRESERVATION_NO;
    }

    public void setROOMRESERVATION_NO(int ROOMRESERVATION_NO) {
        this.ROOMRESERVATION_NO = ROOMRESERVATION_NO;
    }

    public int getROOMRESERVATION_ROOMNO() {
        return ROOMRESERVATION_ROOMNO;
    }

    public void setROOMRESERVATION_ROOMNO(int ROOMRESERVATION_ROOMNO) {
        this.ROOMRESERVATION_ROOMNO = ROOMRESERVATION_ROOMNO;
    }

    public int getROOMRESERVATION_ROOMPRICE() {
        return ROOMRESERVATION_ROOMPRICE;
    }

    public void setROOMRESERVATION_ROOMPRICE(int ROOMRESERVATION_ROOMPRICE) {
        this.ROOMRESERVATION_ROOMPRICE = ROOMRESERVATION_ROOMPRICE;
    }

    public String getROOMRESERVATION_ROOMNAME() {
        return ROOMRESERVATION_ROOMNAME;
    }

    public void setROOMRESERVATION_ROOMNAME(String ROOMRESERVATION_ROOMNAME) {
        this.ROOMRESERVATION_ROOMNAME = ROOMRESERVATION_ROOMNAME;
    }

    public int getROOMRESERVATION_MEMBERNO() {
        return ROOMRESERVATION_MEMBERNO;
    }

    public void setROOMRESERVATION_MEMBERNO(int ROOMRESERVATION_MEMBERNO) {
        this.ROOMRESERVATION_MEMBERNO = ROOMRESERVATION_MEMBERNO;
    }

    public Date getROOMRESERVATION_STAYDAY() {
        return ROOMRESERVATION_STAYDAY;
    }

    public void setROOMRESERVATION_STAYDAY(Date ROOMRESERVATION_STAYDAY) {
        this.ROOMRESERVATION_STAYDAY = ROOMRESERVATION_STAYDAY;
    }

    public Date getROOMRESERVATION_PAYDAY() {
        return ROOMRESERVATION_PAYDAY;
    }

    public void setROOMRESERVATION_PAYDAY(Date ROOMRESERVATION_PAYDAY) {
        this.ROOMRESERVATION_PAYDAY = ROOMRESERVATION_PAYDAY;
    }

    public int getROOMRESERVATION_FOODNO() {
        return ROOMRESERVATION_FOODNO;
    }

    public void setROOMRESERVATION_FOODNO(int ROOMRESERVATION_FOODNO) {
        this.ROOMRESERVATION_FOODNO = ROOMRESERVATION_FOODNO;
    }

    public String getROOMRESERVATION_FOODNAME() {
        return ROOMRESERVATION_FOODNAME;
    }

    public void setROOMRESERVATION_FOODNAME(String ROOMRESERVATION_FOODNAME) {
        this.ROOMRESERVATION_FOODNAME = ROOMRESERVATION_FOODNAME;
    }

    public int getROOMRESERVATION_TOYNO() {
        return ROOMRESERVATION_TOYNO;
    }

    public void setROOMRESERVATION_TOYNO(int ROOMRESERVATION_TOYNO) {
        this.ROOMRESERVATION_TOYNO = ROOMRESERVATION_TOYNO;
    }

    public String getROOMRESERVATION_TOYNAME() {
        return ROOMRESERVATION_TOYNAME;
    }

    public void setROOMRESERVATION_TOYNAME(String ROOMRESERVATION_TOYNAME) {
        this.ROOMRESERVATION_TOYNAME = ROOMRESERVATION_TOYNAME;
    }

    public String getROOMRESERVATION_PICKUPYN() {
        return ROOMRESERVATION_PICKUPYN;
    }

    public void setROOMRESERVATION_PICKUPYN(String ROOMRESERVATION_PICKUPYN) {
        this.ROOMRESERVATION_PICKUPYN = ROOMRESERVATION_PICKUPYN;
    }

    public int getROOMRESERVATION_PICKUPTIME() {
        return ROOMRESERVATION_PICKUPTIME;
    }

    public void setROOMRESERVATION_PICKUPTIME(int ROOMRESERVATION_PICKUPTIME) {
        this.ROOMRESERVATION_PICKUPTIME = ROOMRESERVATION_PICKUPTIME;
    }

    public String getROOMRESERVATION_PICKUPADDRESS() {
        return ROOMRESERVATION_PICKUPADDRESS;
    }

    public void setROOMRESERVATION_PICKUPADDRESS(String ROOMRESERVATION_PICKUPADDRESS) {
        this.ROOMRESERVATION_PICKUPADDRESS = ROOMRESERVATION_PICKUPADDRESS;
    }

    public String getROOMRESERVATION_PICKUPPHONENUM() {
        return ROOMRESERVATION_PICKUPPHONENUM;
    }

    public void setROOMRESERVATION_PICKUPPHONENUM(String ROOMRESERVATION_PICKUPPHONENUM) {
        this.ROOMRESERVATION_PICKUPPHONENUM = ROOMRESERVATION_PICKUPPHONENUM;
    }

    public String getROOMRESERVATION_USEPOINTYN() {
        return ROOMRESERVATION_USEPOINTYN;
    }

    public void setROOMRESERVATION_USEPOINTYN(String ROOMRESERVATION_USEPOINTYN) {
        this.ROOMRESERVATION_USEPOINTYN = ROOMRESERVATION_USEPOINTYN;
    }

    public int getROOMRESERVATION_USEPOINT() {
        return ROOMRESERVATION_USEPOINT;
    }

    public void setROOMRESERVATION_USEPOINT(int ROOMRESERVATION_USEPOINT) {
        this.ROOMRESERVATION_USEPOINT = ROOMRESERVATION_USEPOINT;
    }

    public int getROOMRESERVATION_PLUSPOINT() {
        return ROOMRESERVATION_PLUSPOINT;
    }

    public void setROOMRESERVATION_PLUSPOINT(int ROOMRESERVATION_PLUSPOINT) {
        this.ROOMRESERVATION_PLUSPOINT = ROOMRESERVATION_PLUSPOINT;
    }

    public int getROOMRESERVATION_FIANLFEE() {
        return ROOMRESERVATION_FIANLFEE;
    }

    public void setROOMRESERVATION_FIANLFEE(int ROOMRESERVATION_FIANLFEE) {
        this.ROOMRESERVATION_FIANLFEE = ROOMRESERVATION_FIANLFEE;
    }

}
